[build]
  publish = "carbonnetworksolutions/public"
  command = "cd carbonnetworksolutions && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"